In [1]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

z = np.array([1, 0, 1])

In [2]:
b = A[:2, :2]

C = np.empty_like(A)

In [3]:

for i in range(A.shape[0]):
    C[i] = A[i] + z[i]


In [4]:
X = np.array([[1, 2],
              [3, 4]])

In [5]:
Y = np.array([[5, 6],
              [7, 8]])

In [6]:
v = np.array([9, 10])

In [7]:
addition_result = X + Y
print("Addition of X and Y:\n", addition_result)

Addition of X and Y:
 [[ 6  8]
 [10 12]]


In [8]:
multiplication_result = X @ Y
print("Multiplication of X and Y:\n", multiplication_result)

Multiplication of X and Y:
 [[19 22]
 [43 50]]


In [9]:
sqrt_Y = np.sqrt(Y)
print("Element-wise square root of Y:\n", sqrt_Y)

Element-wise square root of Y:
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [10]:
dot_product = X @ v
print("Dot product of X and v:\n", dot_product)

Dot product of X and v:
 [29 67]


In [11]:
column_sum = np.sum(X, axis=0)
print("Sum of each column of X:\n", column_sum)

Sum of each column of X:
 [4 6]
